name: FastRepair
author: mercurypl
main: mercurypl\FastRepair
api: 5.0.0
version: 1.0.0

permission:
 FastRepair.fix-all.use:
  default: OP
 FastRepair.fix-hand.use:
  default: OP
 FastRepair.fix-all-others.use:
  default: OP
